Do 370 move clearance related components
doubleopen-project/dos pull request #635
Opened 2024-01-04 20:22 UTC by lamppu

2024-01-05 08:31 UTC, Etsija requested changes
Some requests:
1. Could the MainUI's "component headings" all end in colon, as in "Package:", "File:", "Detected license:", "Individual license matches:" etc.
2. All of those should be changed into bold or semibold
3. Use a color for all those headings, to clearly see them "pop up" in MainUI
4. ClearanceInspector: could the bottom-most license conclusion form be bottom-aligned initially?  I know the heights of the sub-panels will eventually be adjusted by the user's preferences, but initially it looks a bit odd for the form to be top-aligned

2024-01-05 11:59 UTC, mmurto requested changes

2024-01-05 11:59 UTC, mmurto commented on apps/clearance_ui/src/styles/globals.css
> +    }
The name of the color does not match the value.

More generally, arbitrary values can be directly used with https://tailwindcss.com/docs/customizing-colors#arbitrary-values.

2024-01-08 09:04 UTC, Etsija approved these changes

2024-01-08 10:34 UTC, mmurto approved these changes

2024-01-08 10:36 UTC, merged