Do 599 new commits
doubleopen-project/dos pull request #745
Opened 2024-03-11 13:18 UTC by Etsija

2024-03-11 13:37 UTC, mmurto requested changes

2024-03-11 13:37 UTC, mmurto commented on scripts/README.md
The cleanup should be merged to the commit that introduces the file.

2024-03-11 13:54 UTC, lamppu commented
Was it decided to not have a color for compound license finding match expressions like "EPL-2.0 OR GPL-2.0-only WITH Classpath-exception-2.0" or were you unaware that these existed? (Sorry if compound is the wrong word, but hopefully you'll get what I mean.) For instance, running with dev:prod, go [here](http://localhost:3000/packages/pkg%3Amaven%2Fjakarta.annotation%2Fjakarta.annotation-api%401.3.5%3Fvcs_type%3DGit%26vcs_url%3Dhttps%253A%252F%252Fgithub.com%252Feclipse-ee4j%252Fcommon-annotations-api.git%26vcs_revision%3D%26resolved_revision%3D77f0aa1760cc4d42d0bab1d59da1bf1b074f1d00/tree/pom.xml?licenseFilter=licenseref-dos-classpath-exception-2.0&filtering=true&licenseMatchId=1189918). There's a couple of examples

2024-03-11 15:19 UTC, lamppu approved these changes

2024-03-12 07:22 UTC, mmurto approved these changes

2024-03-12 07:32 UTC, merged